#!/bin/bash
# XPort — installer for the native messaging host and HTTP daemon (macOS / Linux).
# Usage:
#   ./install.sh <chrome-extension-id>

set -euo pipefail

if [ "$(id -u)" -eq 0 ]; then
  echo "Error: Do not run this script with sudo. It installs to user-level paths."
  exit 1
fi

if [ $# -lt 1 ]; then
  echo "Usage:"
  echo "  $0 <chrome-extension-id>"
  echo ""
  echo "Chrome ID: chrome://extensions (Developer mode)"
  exit 1
fi

EXT_ID="$1"

if [ -z "$EXT_ID" ]; then
  echo "Error: extension ID is required for Chrome installs."
  echo "Find it at chrome://extensions (enable Developer mode)."
  exit 1
fi

HOST_NAME="com.xport.host"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
HOST_PATH="${SCRIPT_DIR}/xport_host.py"

OS="$(uname)"
case "$OS" in
  Darwin)
    TARGET_DIR="$HOME/Library/Application Support/Google/Chrome/NativeMessagingHosts"
    ;;
  Linux)
    TARGET_DIR="$HOME/.config/google-chrome/NativeMessagingHosts"
    ;;
  *)
    echo "Error: Unsupported OS '$OS'. Use install.ps1 on Windows."
    exit 1
    ;;
esac
MANIFEST_PATH="${TARGET_DIR}/${HOST_NAME}.json"

# Verify python3
PYTHON_PATH="$(command -v python3 2>/dev/null || true)"
if [ -z "$PYTHON_PATH" ]; then
  echo "Error: python3 is required but not found in PATH"
  exit 1
fi

# Make host executable
chmod +x "$HOST_PATH"

# --- Generate wrapper script with absolute Python path ---
# Chrome launches native messaging hosts with a minimal environment
# (typically PATH=/usr/bin:/bin:/usr/sbin:/sbin).  The shebang
# #!/usr/bin/env python3 can fail if python3 lives in /usr/local/bin,
# Homebrew, pyenv, or a framework install.  A thin wrapper with absolute
# paths avoids this entirely.
XPORT_DIR_WRAPPER="$HOME/.xport"
WRAPPER_PATH="${XPORT_DIR_WRAPPER}/xport_host_wrapper.sh"

mkdir -p "$XPORT_DIR_WRAPPER"

cat > "$WRAPPER_PATH" <<WRAPPER
#!/bin/sh
# XPort native messaging host wrapper — generated by install.sh
# Launches xport_host.py with an absolute Python path so the native
# messaging protocol works even in Chrome's minimal environment.
exec "${PYTHON_PATH}" "${HOST_PATH}" "\$@"
WRAPPER

chmod +x "$WRAPPER_PATH"

# Create target directory
mkdir -p "$TARGET_DIR"

# Write Chrome native messaging manifest (pointing at the wrapper, not the .py)
cat > "$MANIFEST_PATH" <<EOF
{
  "name": "${HOST_NAME}",
  "description": "XPort native messaging host — bootstraps the local daemon token",
  "path": "${WRAPPER_PATH}",
  "type": "stdio",
  "allowed_origins": ["chrome-extension://${EXT_ID}/"]
}
EOF

echo "Installed native messaging host manifest to:"
echo "  $MANIFEST_PATH"
echo ""
echo "Host wrapper: $WRAPPER_PATH"
echo "Host script: $HOST_PATH"
echo "Python: $PYTHON_PATH"
echo "Extension ID: $EXT_ID"

# --- macOS: install HTTP daemon via launchd ---
if [ "$OS" = "Darwin" ]; then
  DAEMON_PATH="${SCRIPT_DIR}/xport_daemon.py"
  XPORT_DIR="$HOME/.xport"
  XPORT_SECRET="${XPORT_DIR}/secret"
  PLIST_LABEL="com.xport.daemon"
  PLIST_DEST="$HOME/Library/LaunchAgents/${PLIST_LABEL}.plist"
  PLIST_TEMPLATE="${SCRIPT_DIR}/com.xport.daemon.plist"

  chmod +x "$DAEMON_PATH"

  # Create ~/.xport/ with restricted permissions
  mkdir -p "$XPORT_DIR"
  chmod 700 "$XPORT_DIR"

  # Generate auth token if not exists
  if [ ! -f "$XPORT_SECRET" ]; then
    python3 -c "import secrets; print(secrets.token_urlsafe(32))" > "$XPORT_SECRET"
    chmod 600 "$XPORT_SECRET"
    echo "Generated auth token: $XPORT_SECRET"
  else
    echo "Auth token already exists: $XPORT_SECRET"
  fi

  # Unload existing daemon if loaded (ignore errors)
  launchctl bootout "gui/$(id -u)/${PLIST_LABEL}" 2>/dev/null || true
  # Wait for the service to fully unload before re-bootstrapping
  for i in 1 2 3 4 5; do
    launchctl print "gui/$(id -u)/${PLIST_LABEL}" 2>/dev/null || break
    sleep 0.5
  done

  # Capture user's PATH so the daemon can find configured local tools
  USER_PATH="$PATH"
  XPORT_LOG_LEVEL="${XPORT_LOG_LEVEL:-info}"
  XPORT_API_URL="${XPORT_API_URL:-}"
  XPORT_INGEST_TOKEN="${XPORT_INGEST_TOKEN:-}"
  XPORT_TRANSCRIBE_COMMAND="${XPORT_TRANSCRIBE_COMMAND:-}"
  if [ -z "$XPORT_TRANSCRIBE_COMMAND" ] && command -v parakeet-mlx >/dev/null 2>&1 && command -v ffmpeg >/dev/null 2>&1; then
    XPORT_TRANSCRIBE_COMMAND="${SCRIPT_DIR}/xport_transcribe_parakeet.sh"
  fi

  # Substitute plist template
  mkdir -p "$HOME/Library/LaunchAgents"
  sed \
    -e "s|__PYTHON_PATH__|${PYTHON_PATH}|g" \
    -e "s|__DAEMON_PATH__|${DAEMON_PATH}|g" \
    -e "s|__HOME_DIR__|${HOME}|g" \
    -e "s|__PATH__|${USER_PATH}|g" \
    -e "s|__LOG_LEVEL__|${XPORT_LOG_LEVEL}|g" \
    -e "s|__API_URL__|${XPORT_API_URL}|g" \
    -e "s|__INGEST_TOKEN__|${XPORT_INGEST_TOKEN}|g" \
    -e "s|__TRANSCRIBE_COMMAND__|${XPORT_TRANSCRIBE_COMMAND}|g" \
    "$PLIST_TEMPLATE" > "$PLIST_DEST"

  # Load daemon
  launchctl bootstrap "gui/$(id -u)" "$PLIST_DEST"

  echo ""
  echo "HTTP daemon installed:"
  echo "  Plist: $PLIST_DEST"
  echo "  Daemon: $DAEMON_PATH"
  echo "  Listening on: 127.0.0.1:17381"
  echo "  Logs: ${XPORT_DIR}/daemon-stderr.log"
fi

# --- Linux: install HTTP daemon via systemd user service ---
if [ "$OS" = "Linux" ]; then
  DAEMON_PATH="${SCRIPT_DIR}/xport_daemon.py"
  XPORT_DIR="$HOME/.xport"
  XPORT_SECRET="${XPORT_DIR}/secret"
  SERVICE_NAME="com.xport.daemon"
  SERVICE_TEMPLATE="${SCRIPT_DIR}/${SERVICE_NAME}.service"
  SERVICE_DIR="$HOME/.config/systemd/user"
  SERVICE_DEST="${SERVICE_DIR}/${SERVICE_NAME}.service"

  chmod +x "$DAEMON_PATH"

  # Create ~/.xport/ with restricted permissions
  mkdir -p "$XPORT_DIR"
  chmod 700 "$XPORT_DIR"

  # Generate auth token if not exists
  if [ ! -f "$XPORT_SECRET" ]; then
    python3 -c "import secrets; print(secrets.token_urlsafe(32))" > "$XPORT_SECRET"
    chmod 600 "$XPORT_SECRET"
    echo "Generated auth token: $XPORT_SECRET"
  else
    echo "Auth token already exists: $XPORT_SECRET"
  fi

  # Capture user's PATH so the daemon can find configured local tools
  USER_PATH="$PATH"
  XPORT_LOG_LEVEL="${XPORT_LOG_LEVEL:-info}"
  XPORT_API_URL="${XPORT_API_URL:-}"
  XPORT_INGEST_TOKEN="${XPORT_INGEST_TOKEN:-}"
  XPORT_TRANSCRIBE_COMMAND="${XPORT_TRANSCRIBE_COMMAND:-}"
  if [ -z "$XPORT_TRANSCRIBE_COMMAND" ] && command -v parakeet-mlx >/dev/null 2>&1 && command -v ffmpeg >/dev/null 2>&1; then
    XPORT_TRANSCRIBE_COMMAND="${SCRIPT_DIR}/xport_transcribe_parakeet.sh"
  fi

  # Substitute service template
  mkdir -p "$SERVICE_DIR"
  sed \
    -e "s|__PYTHON_PATH__|${PYTHON_PATH}|g" \
    -e "s|__DAEMON_PATH__|${DAEMON_PATH}|g" \
    -e "s|__HOME_DIR__|${HOME}|g" \
    -e "s|__PATH__|${USER_PATH}|g" \
    -e "s|__LOG_LEVEL__|${XPORT_LOG_LEVEL}|g" \
    -e "s|__API_URL__|${XPORT_API_URL}|g" \
    -e "s|__INGEST_TOKEN__|${XPORT_INGEST_TOKEN}|g" \
    -e "s|__TRANSCRIBE_COMMAND__|${XPORT_TRANSCRIBE_COMMAND}|g" \
    "$SERVICE_TEMPLATE" > "$SERVICE_DEST"

  # Reload and enable
  systemctl --user daemon-reload
  systemctl --user enable --now "$SERVICE_NAME"

  echo ""
  echo "HTTP daemon installed:"
  echo "  Service: $SERVICE_DEST"
  echo "  Daemon: $DAEMON_PATH"
  echo "  Listening on: 127.0.0.1:17381"
  echo ""
  echo "Useful commands:"
  echo "  systemctl --user status $SERVICE_NAME"
  echo "  journalctl --user -u $SERVICE_NAME -f"
fi

echo ""
echo "Media/debug directory (set XPORT_OUTPUT_DIR to change):"
echo "  ${XPORT_OUTPUT_DIR:-$HOME/Downloads/xport}"
echo ""
echo "Debug logging (re-run install after setting):"
echo "  export XPORT_LOG_LEVEL=debug"
echo ""
echo "PostgreSQL capture API (re-run install after setting):"
echo "  export XPORT_API_URL=https://xport.example.com"
echo "  export XPORT_INGEST_TOKEN=..."
echo ""
echo "Video transcription (re-run install after setting):"
echo "  export XPORT_TRANSCRIBE_COMMAND=/path/to/transcriber"
if [ -z "${XPORT_TRANSCRIBE_COMMAND:-}" ] && command -v parakeet-mlx >/dev/null 2>&1 && command -v ffmpeg >/dev/null 2>&1; then
  echo "  parakeet-mlx detected; installer will use native-host/xport_transcribe_parakeet.sh by default"
fi
if [ -z "${XPORT_API_URL:-}" ] || [ -z "${XPORT_INGEST_TOKEN:-}" ]; then
  echo ""
  echo "Warning: tweet capture requires XPORT_API_URL and XPORT_INGEST_TOKEN."
fi
